### ISSUE TITLE
Error edgeR : exploreCounts, SARTools release 1.7.4

### ISSUE THREAD

**Issue by mjkaram** [PF2-pasteur-fr/SARTools#85] opened 2021-06-25 11:52 UTC
Hi Hugo,

I have an issue using edgeR via sartools. I get that error message when running the following command:
`exploreCounts(object=out.edgeR$dge, group=target[,varInt], gene.selection=gene.selection, col=colors)`

The error message is:
```
Don't know how to automatically pick scale for object of type function. Defaulting to continuous.
Error: Aesthetics must be valid data columns. Problematic aesthetic(s): label = sample.
Did you mistype the name of a data column or forget to add after_stat()?
Backtrace:
     █
  1. └─SARTools::exploreCounts(...)
  2.   └─SARTools::MDSPlot(...)
  3.     ├─base::print(...)
  4.     └─ggplot2:::print.ggplot(...)
  5.       ├─ggplot2::ggplot_build(x)
  6.       └─ggplot2:::ggplot_build.ggplot(x)
  7.         └─ggplot2:::by_layer(function(l, d) l$compute_aesthetics(d, plot))
  8.           └─ggplot2:::f(l = layers[[i]], d = data[[i]])
  9.             └─l$compute_aesthetics(d, plot)
 10.               └─ggplot2:::f(..., self = self)
Execution halted
```
The column names I use in `target.txt` are 'label', 'files' and 'group'. I don't have any error when running DESeq2 with the same parameters.

Do you know where could that error come from?

Thank you in advance,

Marie-Joe

**Comment by hvaret** [comment] 2021-06-25 12:00
Hi Marie-Joe,
if I understand the message correctly this bug has been fixed in the last version of SARTools (it was due to a change in edgeR). You can try to install SARTools 1.7.4, feel free to let me know the error still occurs.
Best,
Hugo

**Comment by hvaret** [comment] 2021-06-25 12:04
Hi Marie-Joe,
Thanks for your bug report. I made some modifications in SARTools 1.7.4 to extract stuff from edgeR results now structured in a new way. Could you please try to upgrade edgeR and let me know if the problem still occurs?
Best,
Hugo

**Comment by mjkaram** [comment] 2021-06-25 12:15
Thank you Hugo for your quick answer. Actually it is the latest version of SARTools (1.7.4) that is giving me this error.

**Comment by hvaret** [comment] 2021-06-25 13:23
Hi,
which version of edgeR are you using? if it is not the latest, could you try to upgrade?
Hugo

**Comment by mjkaram** [comment] 2021-06-25 13:31
I have edgeR 3.34.0 which is the latest version.
Marie-Joe

**Comment by mjkaram** [comment] 2021-06-25 14:02
Yes indeed I am using limma version 3.48.0. The error raised is probably related to line 22 in https://github.com/PF2-pasteur-fr/SARTools/blob/master/R/MDSPlot.R. Is it a problem in reading the 'sample' column in the 'd' dataframe? I'm wondering if the problem is not related to the fact that `sample` is a function in R.
```
d$sample
 [1] R15-COL-1 R15-COL-2 R15-COL-3 R15-SHA-1 R15-SHA-2 R15-SHA-3 R22-COL-1
 [8] R22-COL-2 R22-COL-3 R22-SHA-1 R22-SHA-2 R22-SHA-3
12 Levels: R15-COL-1 R15-COL-2 R15-COL-3 R15-SHA-1 R15-SHA-2 ... R22-SHA-3
> a=sample
> a
function (x, size, replace = FALSE, prob = NULL) 
{
    if (length(x) == 1L && is.numeric(x) && is.finite(x) && x >= 
        1) {
        if (missing(size)) 
            size <- x
        sample.int(x, size, replace, prob)
    }
    else {
        if (missing(size)) 
            size <- length(x)
        x[sample.int(length(x), size, replace, prob)]
    }
}
<bytecode: 0x55b33cc17040>
<environment: namespace:base>
```
Marie-Joe

**Comment by hvaret** [comment] 2021-06-25 14:10
Right now I do not understand the problem. Could you please send me your data (target and raw counts) and the R script so that I can reproduce the error on my computer?
Hugo

**Comment by hvaret** [comment] 2021-06-28 07:19
Hi,
I have made a test with your data and SARTools 1.7.4 with edgeR and everything is OK. Below is my sessionInfo():
```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.2.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SARTools_1.7.4              kableExtra_1.3.4            ggplot2_3.3.3              
 [4] edgeR_3.34.0                limma_3.48.0                DESeq2_1.32.0              
 [7] SummarizedExperiment_1.22.0 Biobase_2.52.0              MatrixGenerics_1.4.0       
[10] matrixStats_0.59.0          GenomicRanges_1.44.0        GenomeInfoDb_1.28.0        
[13] IRanges_2.26.0              S4Vectors_0.30.0            BiocGenerics_0.38.0        

loaded via a namespace (and not attached):
 [1] bitops_1.0-7           bit64_4.0.5            webshot_0.5.2          RColorBrewer_1.1-2    
 [5] httr_1.4.2             tools_4.1.0            utf8_1.2.1             R6_2.5.0              
 [9] DBI_1.1.1              colorspace_2.0-1       withr_2.4.2            tidyselect_1.1.1      
[13] gridExtra_2.3          GGally_2.1.1           bit_4.0.4              compiler_4.1.0        
[17] rvest_1.0.0            xml2_1.3.2             DelayedArray_0.18.0    ggdendro_0.1.22       
[21] labeling_0.4.2         scales_1.1.1           genefilter_1.74.0      systemfonts_1.0.2     
[25] stringr_1.4.0          digest_0.6.27          rmarkdown_2.8          svglite_2.0.0         
[29] XVector_0.32.0         pkgconfig_2.0.3        htmltools_0.5.1.1      highr_0.9             
[33] fastmap_1.1.0          rlang_0.4.11           rstudioapi_0.13        RSQLite_2.2.7         
[37] generics_0.1.0         farver_2.1.0           BiocParallel_1.26.0    dplyr_1.0.6           
[41] RCurl_1.98-1.3         magrittr_2.0.1         GenomeInfoDbData_1.2.6 Matrix_1.3-4          
[45] Rcpp_1.0.6             munsell_0.5.0          fansi_0.5.0            lifecycle_1.0.0       
[49] stringi_1.6.2          yaml_2.2.1             MASS_7.3-54            zlibbioc_1.38.0       
[53] plyr_1.8.6             grid_4.1.0             blob_1.2.1             ggrepel_0.9.1         
[57] crayon_1.4.1           lattice_0.20-44        Biostrings_2.60.1      splines_4.1.0         
[61] annotate_1.70.0        KEGGREST_1.32.0        locfit_1.5-9.4         knitr_1.33            
[65] pillar_1.6.1           geneplotter_1.70.0     XML_3.99-0.6           glue_1.4.2            
[69] evaluate_0.14          png_0.1-7              vctrs_0.3.8            gtable_0.3.0          
[73] purrr_0.3.4            reshape_0.8.8          assertthat_0.2.1       cachem_1.0.5          
[77] xfun_0.23              xtable_1.8-4           survival_3.2-11        viridisLite_0.4.0     
[81] tibble_3.1.2           AnnotationDbi_1.54.0   memoise_2.0.0          ellipsis_0.3.2
```

**Comment by mjkaram** [comment] 2021-07-07 08:21
Hi Hugo,
Thank you for your answer, I forgot to notice that I installed SARTools via conda. Could the problem come from that?
Here are my  sessionInfo():

```
print(sessionInfo())                                                                                                                        
R version 4.1.0 (2021-05-18)                                                                                                                  
Platform: x86_64-conda-linux-gnu (64-bit)                                                                                                     
Running under: Ubuntu 20.04.2 LTS                                                                                                             
                                                                                                                                              
Matrix products: default                                                                                                                      
BLAS/LAPACK: /home/ubuntu/miniconda3/envs/sartools/lib/libopenblasp-r0.3.15.so                                                                
                                                                                                                                              
locale:                                                                                                                                       
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8                                                                            
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8                                                                        
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C                                                                               
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C                                                                        
                                                                                                                                              
attached base packages:                                                                                                                       
[1] parallel  stats4    stats     graphics  grDevices utils     datasets                                                                      
[8] methods   base                                                                                                                            
                                                                                                                                              
other attached packages:                                                                                                                      
 [1] SARTools_1.7.4              kableExtra_1.3.4                                                                                             
 [3] ggplot2_3.3.5               edgeR_3.34.0                                                                                                 
 [5] limma_3.48.0                DESeq2_1.32.0                                                                                                
 [7] SummarizedExperiment_1.22.0 Biobase_2.52.0                                                                                               
 [9] MatrixGenerics_1.4.0        matrixStats_0.59.0         
[11] GenomicRanges_1.44.0        GenomeInfoDb_1.28.0        
[13] IRanges_2.26.0              S4Vectors_0.30.0           
[15] BiocGenerics_0.38.0        

loaded via a namespace (and not attached):
 [1] ggdendro_0.1.22        httr_1.4.2             viridisLite_0.4.0      
 [4] bit64_4.0.5            splines_4.1.0          BiocManager_1.30.16    
 [7] blob_1.2.1             GenomeInfoDbData_1.2.6 ggrepel_0.9.1          
[10] pillar_1.6.1           RSQLite_2.2.5          lattice_0.20-44        
[13] glue_1.4.2             digest_0.6.27          RColorBrewer_1.1-2     
[16] XVector_0.32.0         rvest_1.0.0            colorspace_2.0-2       
[19] plyr_1.8.6             htmltools_0.5.1.1      Matrix_1.3-4           
[22] XML_3.99-0.6           pkgconfig_2.0.3        genefilter_1.74.0      
[25] zlibbioc_1.38.0        purrr_0.3.4            xtable_1.8-4           
[28] webshot_0.5.2          scales_1.1.1           svglite_2.0.0          
[31] BiocParallel_1.26.0    tibble_3.1.2           annotate_1.70.0        
[34] KEGGREST_1.32.0        generics_0.1.0         ellipsis_0.3.2         
[37] cachem_1.0.5           withr_2.4.2            survival_3.2-11        
[40] magrittr_2.0.1         crayon_1.4.1           memoise_2.0.0          
[43] evaluate_0.14          GGally_2.1.2           fansi_0.5.0            
[46] MASS_7.3-54            xml2_1.3.2             tools_4.1.0            
[49] lifecycle_1.0.0        stringr_1.4.0          munsell_0.5.0          
[52] locfit_1.5-9.4         DelayedArray_0.18.0    AnnotationDbi_1.54.1   
[55] Biostrings_2.60.1      compiler_4.1.0         systemfonts_1.0.2      
[58] rlang_0.4.11           grid_4.1.0             RCurl_1.98-1.3         
[61] rstudioapi_0.13        bitops_1.0-7           rmarkdown_2.9          
[64] gtable_0.3.0           reshape_0.8.8          DBI_1.1.1              
[67] R6_2.5.0               gridExtra_2.3          knitr_1.33             
[70] dplyr_1.0.7            fastmap_1.1.0          bit_4.0.4              
[73] utf8_1.2.1             stringi_1.6.2          Rcpp_1.0.6             
[76] vctrs_0.3.8            geneplotter_1.70.0     png_0.1-7              
```

**Comment by hvaret** [comment] 2021-07-07 11:35
Hi,
yes the problem might come from that. I actually made a small mistake when merging the dev branch with the master, and as bioconda automatically retrieves any new version there might have been a mix. Could you try to install SARTools manually within your environment?
Best,
Hugo

**Comment by mjkaram** [comment] 2021-07-07 12:30
Thank you for your reply, I'll try to install it manually. 
Best,
Marie-Joe

**Closed** 2021-07-29 05:54 UTC
